config/routes.rb
Rails.application.routes.draw do
  get 'brands/spread' => 'brands#spread'
  get 'brands/spread' => 'brands#spread'
  get 'brands/spread' => 'brands#spread'
  get 'brands/spread' => 'brands#spread'

  post 'ambassadors1/:id/update' => 'ambassadors#update'
  post 'ambassadors2/:id/update' => 'ambassadors#update'
  get 'ambassadors1/:id/edit' => 'ambassadors#edit'
  get 'ambassadors2/:id/edit2' => 'ambassadors#edit2'
  get 'ambassadors1/:id' => 'ambassadors#show'
  get 'ambassadors2/:id' => 'ambassadors#show2'

  get 'influencers/new' => 'influencers#new'
  post 'influencers/create' => 'influencers#create'

  get 'login' => 'users#login_form'
  post "login" => "users#login"
  post "logout" => "users#logout"
  get 'users/index'

  get 'posts/flash' => 'posts#flash'
  get 'posts/flash2' => 'posts#flash2'
  get 'posts/new' => 'posts#new'
  get 'posts/index' 
  post "posts/create" => "posts#create"

  post "events/:id/update" => "events#update"
  get "events/:id/edit" => "events#edit"
  post "events/create" => "events#create"
  get "events/new" => "events#new"
  get 'events/index' => 'events#index'
  get 'events/:id' => 'events#show'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
    
end

app/models/influencer.rb
class Influencer < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
    validates :account, {presence: true}
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, {presence: true, uniqueness: true}
    validates :password, {presence: true}
end

app/controllers/ambassadors_controller.rb
class AmbassadorsController < ApplicationController

before_action :set_current_user

  def show
    @ambassador = Event.find_by(id:params[:id])
  end

  def show2
    @ambassador = Event.find_by(id:params[:id])
  end

  def edit
    @ambassador =Event.find_by(id:params[:id])
  end
  
  def edit2
    @ambassador =Event.find_by(id:params[:id])
  end

  def update
    @ambassador = Event.find_by(id: params[:id])

    if params[:amb_content1]
      @ambassador.amb_content1 = params[:amb_content1]
    elsif params[:amb_content2]
      @ambassador.amb_content2 = params[:amb_content2]
    end
    
    if params[:amb_img1]
      @ambassador.amb_img1 = "#{@ambassador.id}_1.jpg"
      image1 = params[:amb_img1]
      File.binwrite("public/amb_images/#{@ambassador.amb_img1}", image1.read)
    elsif params[:amb_img2]
      @ambassador.amb_img2 = "#{@ambassador.id}_2.jpg"
      image2 = params[:amb_img2]
      File.binwrite("public/amb_images/#{@ambassador.amb_img2}", image2.read)
    end
    
    if @ambassador.save
      flash[:notice] = "画像と紹介文章を追加しました"
      redirect_to("/events/index")
    else
      flash[:notice] = “正しく入力してください”
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user
    
    def set_current_user
        @current_user = User.find_by(id:session[:user_id])
    end 
    
    def authenticate_user
        if @current_user == nil
            flash[:notice] = "ログインが必要です"
            redirect_to("/events/index")
        end
    end        
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
    @coming_events = Event.where("start_time>?", Date.today).order("start_time").limit(5)
    @ambassador = Event.find_by(id:params[:id])
  end

  def new
    @event = Event.new
  end

  def show
    @event = Event.find(params[:id])
  end

  def create
    Event.create(event_parameter)
    redirect_to("/events/index")
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to blogs_path, notice:"削除しました"
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(blog_parameter)
      redirect_to blogs_path, notice: "編集しました"
    else
      render 'edit'
    end
  end

  private

  def event_parameter
    params.require(:event).permit(:amb_name1, :amb_img1, :amb_content1, :amb_name2, :amb_img2, :amb_content2, :category, :start_time)
  end
  
end

app/controllers/influencers_controller.rb
class InfluencersController < ApplicationController
  def new
    @influencer = Influencer.new
  end  
  def create
    Influencer.create(influencer_parameter)
    redirect_to("/events/index")
  end

  private

  def influencer_parameter
    params.require(:influencer).permit(:event_name, :account, :category)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user, {only: [:index]}
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find_by(id:params[:id])
  end  

  def new
  end  

  def create
    @post = Post.new(account:params[:account])
    @post.save
    
    if @post.save
      redirect_to("/posts/flash")
      
    else
      redirect_to("/posts/flash2")
      
    end    
     
  end 
  
  def flash
     
  end  

  def flash2
  end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user, {only: [:index]}
  
  def index
    @users = User.all
  end

  def login_form

  end  

  def login
    @user = User.find_by(name:params[:name], password:params[:password])

    if @user
      session[:user_id] = @user.id
      flash[:notice] = "ログインしました"
      redirect_to("/posts/index")
    else
      @error_message = "アカウントまたはパスワードが間違っています"
      render("users/login_form")
    end    
  end
  
  def logout
    session[:user_id] = nil
    flash[:notice] = "ログアウトしました"
    redirect_to("/events/index")
  end  
end

app/views/ambassadors/edit.html.erb
<br><br><br><br><br><br>
<%= form_tag("/ambassadors1/#{@ambassador.id}/update", {multipart: true}) do %>

  <p>紹介文章</p>
  <textarea name="amb_content1"></textarea>
  <br>
  <p>画像</p>
  <input name="amb_img1" type="file">
  <input type="submit" value="保存">
<% end %>  

app/views/ambassadors/edit2.html.erb
<br><br><br><br><br><br>
<%= form_tag("/ambassadors2/#{@ambassador.id}/update", {multipart: true}) do %>

  <p>紹介文章</p>
  <textarea name="amb_content2"></textarea>
  <br>
  <p>画像</p>
  <input name="amb_img2" type="file">
  <input type="submit" value="保存">
<% end %>  

app/views/ambassadors/show.html.erb
<br><br><br><br><br><br>

<div class="center">
  <img src="<%= "/amb_images/#{@ambassador.amb_img1}" %>" class="ambassador-image">
  <p class="text_content"><%= @ambassador.amb_content1 %></p>

  <br><br><br><br>

  <% if @current_user %> 
   <div class="edit_link">  
     <%= link_to("画像と紹介文の追加", "/ambassadors1/#{@ambassador.id}/edit") %>
   </div>  
  <% end %> 
</div>    


  

app/views/ambassadors/show2.html.erb
<br><br><br><br><br><br>

<div class="center">
  <img src="<%= "/amb_images/#{@ambassador.amb_img2}" %>" class="ambassador-image">
  <p class="text_content"><%= @ambassador.amb_content2 %></p>

  <br><br><br><br>

  <% if @current_user %> 
   <div class="edit_link"> 
     <%= link_to("画像と紹介文の追加", "/ambassadors2/#{@ambassador.id}/edit2") %>
   </div>
  <% end %> 
</div>  
  

app/views/events/index.html.erb
<img src="/top-image_new.png" class="top-image">

<br><br><br><br>

<br><br>

<img src="/bland_bg.png" class="top-image">
<a href="/brands/spread"><img src="/spread.png" class="logo-spread"></a>
<img src="/outgoing.png" class="logo-outgoing">
<img src="/influence.png" class="logo-influence">
<img src="/offer_inf.png" class="logo-offer_inf">




<br><br><br><br><br><br><br>

<div class="link-design">
　<a href= "/posts/new" class="btn-square">参加申し込みはこちら</a>
</div>

<br>

<img src="/amb_bg.png" class="top-image">
<a href="https://www.instagram.com/machinegun_yamakita/"><img src="/yamakita.png" class="img-yamakita"></a>
<a href="https://www.instagram.com/kadowakifutago2/"><img src="/yamawaki.png" class="img-yamawaki"></a>


<br><br><br><br><br>

<p id="notice"><%= notice %></p>
<div class="center">
  <h1 class="title-calendar">イベントスケジュール</h1>
</div>

<br>

<%= month_calendar events: @events do |date, events| %>
  <%= date.day %>

  <% events.each do |event| %>
    <div>
      <%= event.category %>
      <br>
      <% unless event.amb_name1 == nil %>
        <%= link_to(event.amb_name1, "/ambassadors1/#{event.id}") %>
      <% end %>  
      <% unless event.amb_name2 == nil %>
        <%= link_to(event.amb_name2, "/ambassadors2/#{event.id}") %>
      <% end %> 
    </div>
  <% end %>
<% end %>

<br>

<h3 class="title-close_event">直近のイベント</h3>
<table class="table-calendar">
  <thead>
    <tr>
      <th>カテゴリー</th>
      <th>時間</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @coming_events.each do |event| %>
      <tr> 　
        <td><%= event.category %></td>
        <td><%= event.start_time.strftime("%Y-%m-%d %H:%M") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<img src="/introduction.png" class="top-image">
<img src="/information.png" class="top-image">

<div class="footer">
      &copy; 2020 JulyFourth
     <br><br><br><br>
</div>

app/views/events/new.html.erb
<%= form_with(model: @event, url: "/events/create", local: true) do |form| %>
    <br>
    <br>
    <div class="title">
      <%= form.label :講師1 %>
      <%= form.text_field :amb_name1 %>
      <%= form.label :何も添付しないでください %>
      <%= form.file_field :amb_img1, class: "image" %>
      <%= form.label :何も入力しないでください %>
      <%= form.text_field :amb_content1 %>
　　  <br>
      <%= form.label :講師2 %>
      <%= form.text_field :amb_name2 %>
      <%= form.label :何も添付しないでください %>
      <%= form.file_field :amb_img2, class: "image" %>
      <%= form.label :何も入力しないでください %>
      <%= form.text_field :amb_content2 %>
    </div>
  
      <div class="time">
      <%= form.label :日時 %>
      <%= form.datetime_select :start_time %>
    </div>
  
    <div class="content">
      <%= form.label :カテゴリー %>
      <%= form.select :category, {"influence":"influence", "outgoing":"outgoing", "spread":"spread", "offer_inf":"offer_inf"} %>
    </div>
  
  
    <div class="submit">
      <%= form.submit %>
    </div>
  
<% end %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>イベント名</strong>
  <%= @event.event_name %>
</p>

<p>
  <strong>時間</strong>
  <%= @event.start_time.strftime("%Y-%m-%d %H:%M") %>
</p>

<p>
  <strong>カテゴリー</strong>
  <%= @event.category %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/influencers/new.html.erb
<%= form_with(model: @influencer, url: "/influencers/create", local: true) do |form| %>
    <br>
    <br>
    <div class="title">
      <%= form.label :event_name %>
      <%= form.text_field :event_name %>
    </div>
  
      <div class="time">
      <%= form.label :インスタアカウント %>
      <%= form.text_field :account %>
    </div>
  
    <div class="content">
      <%= form.label :カテゴリー %>
      <%= form.select :category, {"influence":"influence", "outgoing":"outgoing", "spread":"spread", "offer_inf":"offer_inf"} %>
    </div>
  
  
    <div class="submit">
      <%= form.submit %>
    </div>
  
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Growth</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <ul class="header-menus">
        <%if @current_user %>
         <li>
           <%= link_to 'LPトップページ', '/events/index' %>
         </li>
         <li>
           <%= link_to("参加申込者一覧", "/posts/index") %>
         </li>
         <li>
           <%= link_to 'イベント登録', '/events/new' %>
         </li>
         <li>
           <%= link_to '参加者登録', '/influencers/new' %>
         </li> 
         <li>
           <%= link_to("ログアウト", "/logout", {method: :post}) %>
         </li> 
        <% end %>
      </ul>
    </header>
     

    <%= yield %>

  </body>
</html>

app/views/posts/index.html.erb
<div class="main posts-index">
 
    
  <div class="container">
    <h2>参加者申込一覧</h2>
    <% @posts.each do |post| %>
      <div class="posts-index-item">
        <%= post.account %>
        <br>
        <%= post.created_at %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="main posts-new">
  
    <div class="form-error">
       
    </div>
     
  <div class="container">
    <h1 class="form-heading">申込みフォーム</h1>
    <%= form_tag("/posts/create") do %>
      <div class="form">
        <div class="form-body">
          <p>インスタグラムのアカウントを入力して下さい
          <input name="account"></input>
          <input type="submit" value="送信">
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="main posts-show">
  <div class="container">
    <div class="posts-show-item">
      <p>
        <%= @post.account %>
      </p>
      <div class="post-time">
        <%= @post.created_at %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% @users.each do |user| %>
    <%= user.name %>
<% end %>    

app/views/users/login_form.html.erb
<% if @error_message %>
 <div class="form-error">
  <%= @error_message %>
 </div>
<% end %>  
<%= form_tag("/login") do %> 
 <br>    
 <p>アカウント(name)</p>
 <input name=name>
 <p>パスワード</p>
 <input name=password type=password>
 <input type="submit" value="ログイン">
<% end %>